# Default values for CloudBees Core
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Subdomain -- Whether to use a DNS subdomain for each controller.
Subdomain: true
OperationsCenter:
  # OperationsCenter.Enabled -- Disable for particular use case like setting up namespaces to host masters only
  Enabled: true
  # OperationsCenter.Platform -- Enables specific settings depending on the platform
  # platform specific values are: `eks`, `aws`, `gke`, `aks`, `openshift4`
  Platform: openshift4
  # OperationsCenter.HostName -- The hostname used to access Operations Center through the ingress controller.
  HostName: ci.apps-crc.testing
  License:
    Evaluation:
      # OperationsCenter.License.Evaluation.Enabled -- Obtain a trial evaluation license upon first startup of Operations Center.
      # FirstName, LastName, Email, and Company are all mandatory.
      # Operations Center must be able to contact licenses.cloudbees.com over HTTPS.
      # By using this facility you accept the license agreement: https://www.cloudbees.com/r/subscription
      Enabled: true
      # OperationsCenter.License.Evaluation.FirstName -- first name of evaluating user
      FirstName: admin
      # OperationsCenter.License.Evaluation.LastName -- last name of evaluating user
      LastName: admin
      # OperationsCenter.License.Evaluation.Email -- email address of evaluating user
      Email: acaternberg@cloudbees.com
      # OperationsCenter.License.Evaluation.Company -- company or organization of evaluating user
      Company: cloudbees.com
  # OperationsCenter.Name -- the name in the URL under which Operations Center will be accessible in the given host.
  # For instance, if Subdomain is true, the URL to access Operations Center will be {{OperationsCenter.Protocol}}://{{OperationsCenter.Name}}.{{OperationsCenter.HostName}}:{{OperationsCenter.Port}}
  # If Subdomain is false, the URL to access Operations Center will be {{OperationsCenter.Protocol}}://{{OperationsCenter.HostName}}:{{OperationsCenter.Port}}/{{OperationsCenter.Name}}
  Name: cjoc
  # OperationsCenter.Protocol -- the protocol used to access CJOC. Possible values are http/https.
  Protocol: http
  Route:
    tls:
      # OperationsCenter.Route.tls.Enable -- Set this to true in OpenShift to terminate TLS at route level
      # Read https://docs.openshift.com/container-platform/4.6/networking/routes/secured-routes.html for details.
      # These also apply to Hibernation monitor if enabled.
      Enable: true
Persistence:
  # Persistence.StorageClass -- Persistent Volume Storage Class for Jenkins Home
  # If defined, storageClassName: <storageClass>.
  # If set to "-", storageClassName: "", which disables dynamic provisioning.
  # If undefined (the default) or set to null, the default storage class will be used,
  # unless specified otherwise below.
  # If setting OperationsCenter.Platform == gke, a storage class backed with
  # SSD drives will be created by this chart and used automatically.
  #
  # StorageClass: "-"
  StorageClass: crc-csi-hostpath-provisioner
Common:
  image:
    # Common.image.tag -- container image tag
    tag: '2.462.3.3'
